@startuml Suppression qestion

participant Admin
participant Interface as front
participant Api

Admin -> front: Demande de sélection d'un quiz
activate front

front -> Api: Sélection quiz
activate Api

Api -> Api: Recherche
front <- Api: Envoi du quiz et de ses données
deactivate Api 

Admin <- front: Affichage du contenu du quiz
deactivate front

Admin -> front: Demande d'ajout d'une question
activate front

front -> Api: Demande d'ajout d'une question
activate Api
Api -> Api: Initialise la question


front <- Api: Envoie la page de l'ajout d'une nouvelle question
deactivate Api

Admin <- front: Affiche la page de l'ajout d'une nouvelle question
deactivate front

Admin -> front: Saisir les informations
activate front

front -> Api: Saisir les informations
activate Api

Api -> Api: Traite les informations

front <- Api: Renvoie Status
deactivate Api

Admin <- front: Renvoie Status

deactivate front 


@enduml
