@startuml
Administrator -> Interface: Demander affichage des informations du profil
Interface -> A.P.I: Récupérer données du profil
A.P.I -> A.P.I: Charger données du profil
A.P.I -> Interface: Retourner données du profil
Interface -> Administrator: Afficher informations du profil

alt Modification des informations du profil
  Administrator -> Interface: Modifier informations (e-mail, mot de passe, etc.)
  
  alt Vérification de l'email
    Interface -> Interface: Vérifier format e-mail
    alt Format e-mail incorrect
      Administrator <-- Interface #red: Erreur format e-mail
    else Format e-mail correct
      Interface -> A.P.I: Vérifier existence de l'email
      A.P.I -> A.P.I: Vérifier si e-mail existe déjà
      alt E-mail existant
        Interface <-- A.P.I: Erreur existence e-mail
        Administrator <-- Interface #red: L'email est déjà utilisé
      else E-mail disponible
        Interface -> Interface: Vérifier format mot de passe
        alt Format mot de passe incorrect
          Administrator <-- Interface #red: Erreur format mot de passe
        else Format mot de passe correct
          Administrator -> Interface: Valider modifications
          Interface -> A.P.I: Envoyer modifications (email, mot de passe, etc.)
          A.P.I -> A.P.I: Mettre à jour les données
          A.P.I -> Interface: Confirmer mise à jour
          Interface -> Administrator: Message de confirmation
        end
      end
    end
  end
end

alt Suppression du compte
  Administrator -> Interface: Demander suppression du compte
  Interface -> A.P.I: Envoyer demande de suppression
  A.P.I -> A.P.I: Supprimer données du profil
  A.P.I -> Interface: Confirmer suppression
  Interface -> Administrator: Redirection vers page inscription
  Interface -> Administrator: Message confirmation
end
@enduml
