@startuml Création quiz

participant Admin
participant Interface as front
participant Api

Admin -> front: Clique sur "Créer un quiz"

activate front
Admin <- front: Demande tags, nom, categorie
deactivate front

Admin -> front: Envoie les données
activate front

front -> Api: Créer quiz
activate Api

alt Création réussie
    Api -> Api: Création
    front <- Api: Création faite avec succès
    Admin <- front: Affichage message succès création
else Erreur lors de la création
    Api -> Api: Problème détecté
    front <- Api: Erreur création
    deactivate Api
    Admin <- front: Affichage message échec création

end
deactivate front


@enduml